const fs = require('node:fs');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, 'src/importer.js'), 'utf8');
const sax = fs.readFileSync(require.resolve('sax'), 'utf8');
const bundle = 'const sax = (function (exports) {\n' + sax + '\nreturn exports;\n})({});';
fs.writeFileSync(path.join(__dirname, 'importador-de-planilhas.js'), '// Generated by npm run build. Edit src/importer.js. SAX license: SAX-LICENSE.md\n' + source.replace('/* SAX_PARSER_BUNDLE */', bundle));
