const fs = require('node:fs');
const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const source = fs.readFileSync(require('node:path').join(__dirname, 'importador-de-planilhas.js'),'utf8');
const main = `<!doctype html><html><head><style>body{font:14px Arial;margin:0;color:#33473a}.toolbar{height:110px;padding:20px;background:#f8faf9;border-bottom:1px solid #ddd}#docs-file-menu{display:inline-block;margin-top:18px;cursor:pointer}.grid{height:650px;background-image:linear-gradient(#e6e9e7 1px,transparent 1px),linear-gradient(90deg,#e6e9e7 1px,transparent 1px);background-size:110px 28px}.modal-dialog,.picker-dialog{position:fixed;top:140px;left:300px;width:480px;padding:24px;background:white;box-shadow:0 3px 35px #0003;border:1px solid #ddd}.goog-menu-button{padding:12px;border:1px solid #aaa;cursor:pointer}.goog-menuitem{padding:10px;background:#eee;cursor:pointer}button{padding:12px;background:#137333;color:white;border:0;margin-top:15px}</style></head><body><div class="toolbar"><b>Importação · Planilha de teste</b><br><div id="docs-file-menu" role="menuitem">Arquivo</div></div><div class="grid"></div><script>
window.confirmed=0;
document.getElementById('docs-file-menu').onclick=()=>{const item=document.createElement('div');item.role='menuitem';item.textContent='Importar';document.body.append(item);item.onclick=()=>{item.remove();const picker=document.createElement('div');picker.className='picker-dialog';picker.role='dialog';picker.append((()=>{const n=document.createElement("iframe");n.setAttribute("src","https://drive.google.com/picker");n.setAttribute("style","width:450px;height:150px");n.append();return n;})());document.body.append(picker);}};
window.addEventListener('message',e=>{if(e.origin!=='https://drive.google.com'||e.data?.type!=='fixture-upload')return;window.received=e.data.name;window.receivedText=e.data.text;document.querySelector('.picker-dialog').remove();const dialog=document.createElement('div');dialog.className='modal-dialog';dialog.role='dialog';dialog.append((()=>{const n=document.createElement("h2");n.append("Importar arquivo");return n;})(),(()=>{const n=document.createElement("p");n.append("Local de importação");return n;})(),(()=>{const n=document.createElement("div");n.setAttribute("role","listbox");n.setAttribute("aria-label","Local de importação");n.setAttribute("class","goog-menu-button");n.append((()=>{const n=document.createElement("span");n.setAttribute("class","goog-menu-button-caption");n.append("Criar nova planilha");return n;})(),(()=>{const n=document.createElement("span");n.append("▼");return n;})());return n;})(),(()=>{const n=document.createElement("button");n.append("Importar dados");return n;})());document.body.append(dialog);dialog.querySelector('button').onclick=()=>{window.confirmed++;};const dropdown=dialog.querySelector('.goog-menu-button');dropdown.onclick=()=>{const menu=document.createElement('div');menu.role='listbox';for(const text of ['Criar nova planilha','Substituir página atual','Inserir nova(s) página(s)','Substituir planilha']){const option=document.createElement('div');option.className='goog-menuitem';option.role='option';option.textContent=text;option.onclick=()=>{dropdown.querySelector('.goog-menu-button-caption').textContent=text;window.destination=text;menu.remove();};menu.append(option);}document.body.append(menu);};});
</script></body></html>`;
const picker = '<html><body><button role="tab">Upload</button><input type="file" accept=".csv,.xlsx" hidden><script>document.querySelector("input").addEventListener("change",async e=>{window.top.postMessage({type:"fixture-upload",name:e.target.files[0].name,text:await e.target.files[0].text()},"https://docs.google.com");});</script></body></html>';
(async()=>{
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-software-rasterizer','--use-gl=angle','--use-angle=swiftshader']});
const context=await browser.newContext({viewport:{width:1366,height:768}});
await context.route('**/*',async route=>{
 const url=route.request().url();
 if(url==='https://docs.google.com/spreadsheets/d/test-sheet/edit')return route.fulfill({headers:{'Content-Security-Policy':"require-trusted-types-for 'script'; trusted-types 'none'"},contentType:'text/html; charset=utf-8',body:main});
 if(url==='https://drive.google.com/picker')return route.fulfill({headers:{'Content-Security-Policy':"require-trusted-types-for 'script'; trusted-types 'none'"},contentType:'text/html; charset=utf-8',body:picker+'<script>'+source+'</script>'});
 return route.abort();
});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('https://docs.google.com/spreadsheets/d/test-sheet/edit');await page.evaluate(source);
await page.evaluate(()=>{const transfer=new DataTransfer();transfer.items.add(new File(['id,quantidade\nBR0123,20'],'recebimento.csv',{type:'text/csv'}));document.querySelector('.grid').dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:transfer}));});
await page.getByRole('button',{name:'Continuar',exact:true}).waitFor();

await page.getByRole('button',{name:'Continuar',exact:true}).click();
try { await page.waitForFunction(()=>window.destination==='Inserir nova(s) página(s)',null,{timeout:8000}); } catch(e) { console.log(await page.evaluate(()=>({status:document.querySelector('[data-spx-importer]').shadowRoot.querySelector('.status').textContent,received:window.received,destination:window.destination,body:document.body.innerText,frames:window.frames.length}))); console.log(errors); console.log(await Promise.all(page.frames().map(async f=>({url:f.url(),data:await f.evaluate(()=>({worker:window.__spxSheetsImporter,body:document.body.innerText})).catch(()=>null)}))));  await browser.close(); throw e; }
assert.equal(await page.evaluate(()=>window.received),'recebimento.csv');assert.equal(await page.evaluate(()=>window.confirmed),0);
assert.deepEqual(errors,[]);
await assert.rejects(page.evaluate(()=>{document.createElement('div').attachShadow({mode:'open'}).innerHTML='<p>blocked</p>';}), /TrustedHTML/);
await page.setViewportSize({width:390,height:720});await page.getByRole('button',{name:'Importar',exact:true}).click();

await page.goto('https://docs.google.com/spreadsheets/d/test-sheet/edit');await page.evaluate(source);await page.getByRole('button',{name:'Importar',exact:true}).click();await page.locator('input[type=file]').setInputFiles({name:'dados.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(fs.readFileSync(require('node:path').join(__dirname,'fixtures/dados.xlsx.base64'),'utf8'),'base64')});await page.waitForFunction(()=>!document.querySelector('[data-spx-importer]').shadowRoot.querySelector('.start').disabled);await page.locator('input[value=current]').check();await page.locator('.sheet').selectOption('1');await page.getByRole('button',{name:'Continuar',exact:true}).click();await page.waitForFunction(()=>window.destination==='Substituir página atual',null,{timeout:10000});assert.equal(await page.evaluate(()=>window.received),'Expedição.csv');assert.equal(await page.evaluate(()=>window.receivedText),'"BR456","7"');assert.equal(await page.evaluate(()=>window.confirmed),0);assert.deepEqual(errors,[]);await browser.close();console.log('Chromium QA passed: actual compressed XLSX conversion, chosen sheet CSV, whole-sheet drop, iframe upload on drive.google.com, Google-style dropdown, selected insert destination, no automatic confirmation, no browser errors. Trusted Types enforced with policies disabled.');
})().catch(e=>{console.error(e);process.exit(1);});
